#!/usr/bin/env python
import rospy
from jetbot import Robot


class Spinner():
  def __init__(self):
    self.robot = Robot()

  def spin_forever(self, angular_speed = 0.3):
    self.robot.right(speed = angular_speed)


def main():
  rospy.init_node('spin')
  params = rospy.get_param("~params", {})

  try:
      spinner = Spinner()
      spinner.spin_forever(params.get("angular_speed", 0.3))
  except rospy.ROSInterruptException:
      pass


if __name__ == "__main__":
  main()
